version: '3'
services:
  web:
    build: .
    ports:
      - "7893:7893"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    command: --init-file /data/application/init.sql
volumes:
  db_data:
