version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: liberatube
    ports:
      - "7893:80"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  db-data: