name: Bug report
description: Found a bug? Share it here.
title: "[Bug] <>"
assignees: 
  - GoldDominik893
  
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "Example: v1.6, please also include whether it is the dev channel or stable"
    validations:
      required: true

  - type: textarea
    id: more-infos
    attributes:
      label: Steps needed to reproduce this bug.
      placeholder: "Example: Go to settings, Set theme to light mode."
    validations:
      required: true
