name: New instance
description: New public instance proposal form
title: "[New instance] <instance name>"
assignees: 
  - GoldDominik893

body:
  - type: input
    id: url
    attributes:
      label: URL
      description: "the URL of your instance"
      placeholder: "Example: https://lt.example.com"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Mandatory checks
      description: "Your instance must fulfill all the conditions listed below in order to be accepted"
      options:
      - label: "Instance has a domain name"
        required: true
      - label: "Instance is served over HTTPS"
        required: true
      - label: "Instance is properly configured"
        required: true
      - label: "Instance has been running for at least 30 days."
        required: true
        

  - type: checkboxes
    attributes:
      label: Maintainer chart
      description: "As a maintainer, I acknowledge that I must do the following to stay in the public list"
      options:
      - label: "Ensure that my instance is up to date (less than one month old)"
        required: true
      - label: "Ensure a proper uptime of my instance (around 90%)"
        required: true

  - type: input
    id: country
    attributes:
      label: Host country
      description: What country is the instance hosted in?
      placeholder: "Example: North Korea"
    validations:
      required: true

  - type: input
    id: mitm-name
    attributes:
      label: Man in the Middle
      description: "If your instance is behind a DDoS protection or MitM system, please specify that here"
      placeholder: "Example: Cloudflare"
    validations:
      required: false

  - type: input
    id: source-code-url
    attributes:
      label: Source code URL
      description: "If your instance is running a modified source code, please provide the URL below"
      placeholder: "Example: https://git.example.com/you/liberatube"
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Analytics
      description: "If your instance is running analytics:"
      options:
      - label: "They are GDPR/CCPA compliant"
        required: false
      - label: "This is stated in your Privacy Policy"
        required: false
      - label: "You have provided the source code's URL in the dedicated field above"
        required: false

  - type: textarea
    id: more-infos
    attributes:
      label: Additional information
      description: "If you want to add other information on your instance, do so here:"
      placeholder: "Example: Our instance also has an .i2p URL, The source code changes are ..., etc."
    validations:
      required: false
