name: Build arm64 image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push ARM64 Docker image
        run: |
          docker compose build
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/arm64 --push -t docker.io/golddominik893/liberatube:latest-arm64 .
